name: Sync S3 with Github

on:
  push:
    branches:
      - main

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    timeout-minutes: 5
    name: Copy changed files to S3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  
        with:
          fetch-depth: 2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1    
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Copy files to s3
        run: |
          for file in $(git diff --name-only HEAD^ HEAD); do   
            aws s3 cp $file ${{ secrets.AWS_S3_BUCKET_PROD }}/$file
          done
